Add support for multilayered images

diff --git a/archiso/initcpio/hooks/archiso b/archiso/initcpio/hooks/archiso
--- a/archiso/initcpio/hooks/archiso
+++ b/archiso/initcpio/hooks/archiso
@@ -3,54 +3,13 @@
 # SPDX-License-Identifier: GPL-3.0-or-later
 
 # args: source, newroot, mountpoint
-_mnt_dmsnapshot() {
-    local img="${1}"
-    local newroot="${2}"
-    local mnt="${3}"
-    local img_fullname="${img##*/}";
-    local img_name="${img_fullname%%.*}"
-    local dm_snap_name="${dm_snap_prefix}_${img_name}"
-    local ro_dev ro_dev_size rw_dev
-
-    ro_dev="$(losetup --find --show --read-only -- "${img}")"
-    echo "${ro_dev}" >> /run/archiso/used_block_devices
-    ro_dev_size="$(blockdev --getsz "${ro_dev}")"
-
-    if [ "${cow_persistent}" = "P" ]; then
-        if [ -f "/run/archiso/cowspace/${cow_directory}/${img_name}.cow" ]; then
-            msg ":: Found '/run/archiso/cowspace/${cow_directory}/${img_name}.cow', using as persistent."
-        else
-            msg ":: Creating '/run/archiso/cowspace/${cow_directory}/${img_name}.cow' as persistent."
-            truncate -s "${cow_spacesize}" "/run/archiso/cowspace/${cow_directory}/${img_name}.cow"
-        fi
-    else
-        if [ -f "/run/archiso/cowspace/${cow_directory}/${img_name}.cow" ]; then
-            msg ":: Found '/run/archiso/cowspace/${cow_directory}/${img_name}.cow' but non-persistent requested, removing."
-            rm -f "/run/archiso/cowspace/${cow_directory}/${img_name}.cow"
-        fi
-        msg ":: Creating '/run/archiso/cowspace/${cow_directory}/${img_name}.cow' as non-persistent."
-        truncate -s "${cow_spacesize}" "/run/archiso/cowspace/${cow_directory}/${img_name}.cow"
-    fi
-
-    rw_dev="$(losetup --find --show "/run/archiso/cowspace/${cow_directory}/${img_name}.cow")"
-    echo "${rw_dev}" >> /run/archiso/used_block_devices
-
-    dmsetup create "${dm_snap_name}" --table \
-        "0 ${ro_dev_size} snapshot ${ro_dev} ${rw_dev} ${cow_persistent} ${cow_chunksize}"
-
-    if [ "${cow_persistent}" != "P" ]; then
-        rm -f "/run/archiso/cowspace/${cow_directory}/${img_name}.cow"
-    fi
-
-    _mnt_dev "/dev/mapper/${dm_snap_name}" "${newroot}${mnt}" "-w" "defaults"
-    readlink -f "/dev/mapper/${dm_snap_name}" >> /run/archiso/used_block_devices
-}
-
-# args: source, newroot, mountpoint
 _mnt_overlayfs() {
     local src="${1}"
     local newroot="${2}"
     local mnt="${3}"
+
+    msg ":: OverlayFS SRC: ${src}, NEWROOT: ${newroot}, MNT: ${mnt}..."
+
     mkdir -p "/run/archiso/cowspace/${cow_directory}/upperdir" "/run/archiso/cowspace/${cow_directory}/workdir"
     mount -t overlay -o \
     "lowerdir=${src},upperdir=/run/archiso/cowspace/${cow_directory}/upperdir,workdir=/run/archiso/cowspace/${cow_directory}/workdir" \
@@ -81,12 +40,36 @@ _mnt_sfs() {
     _mnt_dev "${sfs_dev}" "${mnt}" "-r" "defaults"
 }
 
+# args: /path/to/image_file, mountpoint
+_mnt_erofs() {
+    local img="${1}"
+    local mnt="${2}"
+    local img_fullname="${img##*/}"
+    local erofs_dev
+
+    # shellcheck disable=SC2154
+    # defined via initcpio's parse_cmdline()
+    if [ "${copytoram}" = "y" ]; then
+        msg -n ":: Copying EROFS image to RAM..."
+        if ! cp -- "${img}" "/run/archiso/copytoram/${img_fullname}" ; then
+            echo "ERROR: while copy '${img}' to '/run/archiso/copytoram/${img_fullname}'"
+            launch_interactive_shell
+        fi
+        img="/run/archiso/copytoram/${img_fullname}"
+        msg "done."
+    fi
+    erofs_dev="$(losetup --find --show --read-only -- "${img}")"
+    echo "${erofs_dev}" >> /run/archiso/used_block_devices
+    _mnt_dev "${erofs_dev}" "${mnt}" "-r" "defaults" "erofs"
+}
+
 # args: device, mountpoint, flags, opts
 _mnt_dev() {
     local dev="${1}"
     local mnt="${2}"
     local flg="${3}"
     local opts="${4}"
+    local fstype="${5:-auto}"
 
     mkdir -p "${mnt}"
 
@@ -99,7 +82,7 @@ _mnt_dev() {
         launch_interactive_shell
     done
 
-    if mount -o "${opts}" "${flg}" "${dev}" "${mnt}"; then
+    if mount -t "${fstype}" -o "${opts}" "${flg}" "${dev}" "${mnt}"; then
         msg ":: Device '${dev}' mounted successfully."
     else
         echo "ERROR; Failed to mount '${dev}'"
@@ -120,14 +103,17 @@ _verify_checksum() {
 
 _verify_signature() {
     local _status
+    local sigfile="${1}"
     cd "/run/archiso/bootmnt/${archisobasedir}/${arch}" || exit 1
-    gpg --homedir /gpg --status-fd 1 --verify airootfs.sfs.sig 2>/dev/null | grep -qE '^\[GNUPG:\] GOODSIG'
+    gpg --homedir /gpg --status-fd 1 --verify "${sigfile}" 2>/dev/null | grep -qE '^\[GNUPG:\] GOODSIG'
     _status=$?
     cd -- "${OLDPWD}" || exit 1
     return ${_status}
 }
 
 run_hook() {
+    msg ":: Loading archiso..."
+
     [ -z "${arch}" ] && arch="$(uname -m)"
     [ -z "${copytoram_size}" ] && copytoram_size="75%"
     [ -z "${archisobasedir}" ] && archisobasedir="arch"
@@ -160,6 +146,11 @@ run_hook() {
 # args: /path/to/newroot
 archiso_mount_handler() {
     local newroot="${1}"
+    local sigfile
+    local layerfile
+    local layer_dir=""
+
+    msg ":: Mounting boot device, please wait..."
 
     if ! mountpoint -q "/run/archiso/bootmnt"; then
         _mnt_dev "${archisodevice}" "/run/archiso/bootmnt" "-r" "defaults"
@@ -168,40 +159,9 @@ archiso_mount_handler() {
         fi
     fi
 
-    # shellcheck disable=SC2154
-    # defined via initcpio's parse_cmdline()
-    if [ "${checksum}" = "y" ]; then
-        if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sha512" ]; then
-            msg -n ":: Self-test requested, please wait..."
-            if _verify_checksum; then
-                msg "done. Checksum is OK, continue booting."
-            else
-                echo "ERROR: one or more files are corrupted"
-                echo "see /tmp/checksum.log for details"
-                launch_interactive_shell
-            fi
-        else
-            echo "ERROR: checksum=y option specified but ${archisobasedir}/${arch}/airootfs.sha512 not found"
-            launch_interactive_shell
-        fi
-    fi
+    msg ":: Loading layers..."
 
-    # shellcheck disable=SC2154
-    # defined via initcpio's parse_cmdline()
-    if [ "${verify}" = "y" ]; then
-        if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs.sig" ]; then
-            msg -n ":: Signature verification requested, please wait..."
-            if _verify_signature; then
-                msg "done. Signature is OK, continue booting."
-            else
-                echo "ERROR: one or more files are corrupted"
-                launch_interactive_shell
-            fi
-        else
-            echo "ERROR: verify=y option specified but ${archisobasedir}/${arch}/airootfs.sfs.sig not found"
-            launch_interactive_shell
-        fi
-    fi
+    layerfile="/run/archiso/bootmnt/${archisobasedir}/layers.${arch}.txt"
 
     if [ "${copytoram}" = "y" ]; then
         msg ":: Mounting /run/archiso/copytoram (tmpfs) filesystem, size=${copytoram_size}"
@@ -221,15 +181,78 @@ archiso_mount_handler() {
     mkdir -p "/run/archiso/cowspace/${cow_directory}"
     chmod 0700 "/run/archiso/cowspace/${cow_directory}"
 
-    _mnt_sfs "/run/archiso/bootmnt/${archisobasedir}/${arch}/airootfs.sfs" "/run/archiso/sfs/airootfs"
-    if [ -f "/run/archiso/sfs/airootfs/airootfs.img" ]; then
-        _mnt_dmsnapshot "/run/archiso/sfs/airootfs/airootfs.img" "${newroot}" "/"
-    else
-        _mnt_overlayfs "/run/archiso/sfs/airootfs" "${newroot}" "/"
-    fi
+    mkdir -p /run/archiso/layers
+
+    msg ":: Start to checking layers integrity..."
+
+    # inverse loop into layers file to mount then and create lowerdir list
+    while read -r LINE; do
+        local layer_name="${LINE}"
+        msg ":: Loading layer ${layer_name}..."
+
+        # shellcheck disable=SC2154
+        # defined via initcpio's parse_cmdline()
+        if [ "${checksum}" = "y" ]; then
+            if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/${layer_name}.sha512" ]; then
+                msg -n ":: Self-test requested for ${layer_name}, please wait..."
+                if _verify_checksum; then
+                    msg "done. Checksum is OK for ${layer_name}, continue booting."
+                else
+                    echo "ERROR: one or more files are corrupted for ${layer_name}"
+                    echo "see /tmp/checksum.log for details"
+                    launch_interactive_shell
+                fi
+            else
+                echo "ERROR: checksum=y option specified but ${archisobasedir}/${arch}/${layer_name}.sha512 not found"
+                launch_interactive_shell
+            fi
+        fi
+
+        # shellcheck disable=SC2154
+        # defined via initcpio's parse_cmdline()
+        if [ "${verify}" = "y" ]; then
+            if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/${layer_name}.sfs.sig" ]; then
+                sigfile="${layer_name}.sfs.sig"
+            elif [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/${layer_name}.erofs.sig" ]; then
+                sigfile="${layer_name}.erofs.sig"
+            fi
+            if [ -n "${sigfile}" ]; then
+                msg -n ":: Signature verification requested for ${layer_name}, please wait..."
+                if _verify_signature "${sigfile}"; then
+                    msg "done. Signature is OK for ${layer_name}, continue booting."
+                else
+                    echo "ERROR: one or more files are corrupted in ${layer_name}"
+                    launch_interactive_shell
+                fi
+            else
+                echo "ERROR: verify=y option specified but GPG signature not found for ${layer_name} in ${archisobasedir}/${arch}/"
+                launch_interactive_shell
+            fi
+        fi
+
+        if [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/${layer_name}.sfs" ]; then
+            _mnt_sfs "/run/archiso/bootmnt/${archisobasedir}/${arch}/${layer_name}.sfs" "/run/archiso/layers/${layer_name}"
+        elif [ -f "/run/archiso/bootmnt/${archisobasedir}/${arch}/${layer_name}.erofs" ]; then
+            _mnt_erofs "/run/archiso/bootmnt/${archisobasedir}/${arch}/${layer_name}.erofs" "/run/archiso/layers/${layer_name}"
+        fi
+
+        if [ "${layer_dir}" = "" ]; then
+            layer_dir="/run/archiso/layers/${layer_name}"
+        else
+            layer_dir="${layer_dir}:/run/archiso/layers/${layer_name}"
+        fi
+
+    done << EOF
+$(tac "$layerfile")
+EOF
+
+    msg ":: Load OverlayFS with layers ${layer_dir}..."
+
+    _mnt_overlayfs "${layer_dir}" "${newroot}" "/"
 
     if [ "${copytoram}" = "y" ]; then
         umount -d /run/archiso/bootmnt
+        rmdir /run/archiso/bootmnt
     fi
 }
 
